# Generated by Django 4.2.20 on 2025-04-02 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_perspective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perspective',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
