# Generated by Django 4.2.20 on 2025-04-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_perspective_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
