# Generated by Django 4.2.20 on 2025-04-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_perspective_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='description_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perspective',
            name='description_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perspective',
            name='description_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perspective',
            name='description_4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perspective',
            name='description_5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='perspective',
            name='description_6',
            field=models.TextField(blank=True, default=''),
        ),
    ]
