# Generated by Django 4.2.20 on 2025-05-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_perspective_description_1_perspective_description_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perspective',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='description',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='description_6',
        ),
        migrations.RemoveField(
            model_name='perspective',
            name='name',
        ),
        migrations.AddField(
            model_name='perspective',
            name='title',
            field=models.CharField(default='Untitled perspective', max_length=100),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'Texto livre'), ('int', 'Número inteiro'), ('choice', 'Opção de lista')], max_length=10)),
                ('int_min', models.IntegerField(blank=True, null=True)),
                ('int_max', models.IntegerField(blank=True, null=True)),
                ('perspective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='projects.perspective')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='projects.label')),
            ],
            options={
                'ordering': ['pk'],
                'unique_together': {('label', 'value')},
            },
        ),
    ]
