# Generated by Django 4.2.20 on 2025-06-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_label_labelperspective'),
    ]

    operations = [
        migrations.AddField(
            model_name='perspective',
            name='description',
            field=models.CharField(default='No details yet', max_length=1000),
        ),
    ]
