# Generated by Django 4.2.15 on 2025-06-13 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0014_rename_label_labelperspective"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerspectiveResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("string_value", models.TextField(blank=True, null=True)),
                ("int_value", models.IntegerField(blank=True, null=True)),
                (
                    "choice_value",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="projects.choiceoption"
                    ),
                ),
                (
                    "perspective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="projects.perspective"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perspective_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("perspective", "user")},
            },
        ),
    ]
