# Generated by Django 4.2.20 on 2025-06-13 02:04

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_perspective_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perspective',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('project'), name='uniq_persp_title_per_project_i'),
        ),
    ]
