# Generated by Django 4.2.15 on 2025-06-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0015_perspectiveresponse"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="perspectiveresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="perspectiveresponse",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="projects.labelperspective",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="perspectiveresponse",
            unique_together={("perspective", "user", "label")},
        ),
    ]
