# Generated by Django 4.2.20 on 2025-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0008_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='has_discrepancy',
            field=models.BooleanField(default=False, help_text='Flag indicando se houve divergência entre labels de usuários'),
        ),
        migrations.AddField(
            model_name='example',
            name='label_counts',
            field=models.JSONField(blank=True, default=dict, help_text='Contagem de votos por label'),
        ),
        migrations.AddField(
            model_name='example',
            name='label_percentages',
            field=models.JSONField(blank=True, default=dict, help_text='Percentual de votos por label'),
        ),
        migrations.AddField(
            model_name='example',
            name='labels_by_user',
            field=models.JSONField(blank=True, default=dict, help_text='Mapa de user_id → label aplicado a este exemplo'),
        ),
    ]
