# Generated by Django 4.2.20 on 2025-04-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0009_example_has_discrepancy_example_label_counts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='has_discrepancy',
        ),
        migrations.RemoveField(
            model_name='example',
            name='label_counts',
        ),
        migrations.RemoveField(
            model_name='example',
            name='label_percentages',
        ),
        migrations.RemoveField(
            model_name='example',
            name='labels_by_user',
        ),
    ]
