# Generated by Django 4.2.20 on 2025-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0012_discussion_rule_rulevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
