# Generated by Django 4.2.20 on 2025-05-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0014_discussionmessagediscussion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionMessageDiscussion',
        ),
    ]
