# Generated by Django 4.2.20 on 2025-05-23 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0015_delete_discussionmessagediscussion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='examples.discussion')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['discussion', 'created_at'], name='examples_di_discuss_8bf4e2_idx')],
            },
        ),
    ]
